- src/react/components/screen/screen-body.tsx
This PR enables an optional `title` prop for a `ScreenBody`. For advanced layouts, the title may sometimes need to be contained in a wrapper outside of `ScreenBody`.
[See corresponding PR in `blockstack-app`](https://github.com/blockstack/blockstack-app/pull/68)
> fix: Allow optional title

- src/popup.ts
- src/react/components/screens/intro.tsx
Closes #11
This PR aims to ensure the auth pop up covers the modal open within the viewport. 
It is not a fool-proof solution, there are some edge cases where it doesn't work perfectly. This complexity is owed to the fact the popup opens relative to the screen, not the browser viewport.
Below is a reasonably complex example. The window is centred in the screen, and a browser side panel is open, all of these need to be factored into the calculation of which coordinate the window should open on.
**Note**: if you try this out with dev tools open, _it will_ open in the wrong position. This is because of the `outerWidth - innerWidth` calculation. I figure regular users will more often have a left side panel open than a right one.
We might be able to cover some more edge cases using the …
> refactor: Attempted improvement of browser popup opening position

- .eslintrc.js
- package.json
- src/react/components/checklist/index.tsx
- src/react/components/screen/screen-actions.tsx
- src/react/components/screen/screen-body.tsx
- src/react/components/screen/screen-header.tsx
- src/react/components/screen/screen.tsx
- src/react/components/screens/finished.tsx
- src/react/components/screens/intro.tsx
- src/react/components/typography/index.tsx
- yarn.lock
- This PR changes the way that `Screen` spaces out objects. We are now using `Stack` instead of `Flex` as the main wrapper component, with a spacing prop of `3` provided.
- `ScreenActions` has been updated to allow for props to be passed to the underlying `Flex` element, and some spacing adjustments have been made.
- `ScreenHeader` has been updated to allow us to hide only the logo, or only the appIcon if we choose to.
- the loading state no longer affects the UI.
- Added and adjusted the checklist content describing the benefits of Data Vault
Connected to this [blockstack-app PR](https://github.com/blockstack/blockstack-app/pull/69).
> Update screen components

- src/popup.ts
- src/react/components/checklist/index.tsx
- src/react/components/checkmark.tsx
- src/react/components/link.tsx
- src/react/components/modal/index.tsx
- src/react/components/screen/screen-body.tsx
- src/react/components/screen/screen-header.tsx
- src/react/components/screen/screen.tsx
- src/react/components/screens/finished.tsx
- src/react/components/screens/how-it-works.tsx
- src/react/components/screens/intro.tsx
- src/react/components/screens/sign-in.tsx
- src/react/components/typography/index.tsx
- webpack.config.js
Fixes https://github.com/blockstack/blockstack-app/issues/72
Fixes https://github.com/blockstack/blockstack-app/issues/82
Fixes https://github.com/blockstack/blockstack-app/issues/73
Fixes https://github.com/blockstack/blockstack-app/issues/75
Fixes https://github.com/blockstack/blockstack-app/issues/74
Fixes https://github.com/blockstack/blockstack-app/issues/78
Fixes https://github.com/blockstack/blockstack-app/issues/84
> fix: Spacing of new auth flow

- src/react/hooks/use-scroll-lock.tsx
Banter broke because importing `connect` tries to use `window`. This changes the code to only use `window` if available.
> fix: only use window for scroll lock if available

- .npmignore
- package.json
- test-app/package.json
- test-app/yarn.lock
- tsdx.config.js
- yarn.lock
While working on bundle size for the app, I saw that we were including styled-components entirely in here, we don't need to do that.
> build: update deps and prevent styled-components from being bundled

- src/auth.ts
The app has a (short) timeout, while it waits to see if it can use message passing to finish auth. This adds a `window.focus()` call, so that even if the app doesn't close, we can still grab focus right after auth.
> feat: window.focus() after auth finished

- .changeset/long-crabs-work.md
- packages/connect-react/src/react/hooks/use-connect.ts
- packages/connect/src/transactions/index.ts
- packages/connect/src/types/provider.ts
- packages/connect/src/types/transactions.ts
Adding support for `sponsored` transaction prop, https://github.com/blockstack/connect/issues/99
No
Work can be tracked here: https://github.com/blockstack/docs/issues/1133
> feat: add sponsored field

- .changeset/lazy-foxes-tap.md
- packages/connect-ui/src/components/modal/modal.tsx
This PR changes the url path for installing the web wallet Chrome extension. Now that the wallet will be available for install in the app store, we no longer want to route users to the hiro.so path.
For details refer to issue #96
No.
No.
Provide context on how tests should be performed.
1. Is testing required for this change?
TBD
> refactor: change url for chrome ext install

- .changeset/funny-mayflies-wait.md
- packages/connect-ui/src/components.d.ts
- packages/connect-ui/src/components/modal/modal.scss
- packages/connect-ui/src/components/modal/modal.tsx
- packages/connect-ui/src/components/modal/readme.md
- packages/connect-ui/src/index.html
- packages/connect/package.json
- packages/connect/src/ui.ts
This PR fixes a bug in the modal prompting users to install the stacks wallet which was not allowing them to close the modal. Now, clicking on the `X` to close the modal is working.
For details refer to issue #123
No.
No.
- Use the test-app and do not have the web wallet installed
- Click to sign up
- The `X` button should now close the modal
> fix: handle closing the install prompt modal

- .changeset/stupid-humans-promise.md
- packages/connect/src/auth.ts
- packages/connect/src/transactions/index.ts
- packages/connect/src/types/auth.ts
- packages/connect/src/types/transactions.ts
This PR adds an `onCancel` callback function to a transaction. It also adds a boolean on the tx payload to check if the callback function should be run.
Ex. `onCancel` will be called when a user closes/cancels a transaction window.
`stacks-web-wallet`:
Issue: https://github.com/blockstack/stacks-wallet-web/issues/959
PR: https://github.com/blockstack/stacks-wallet-web/pull/1175
No.
No.
TBD.
> feat: support onCancel

- .changeset/chilly-guests-punch.md
- packages/connect-ui/src/components/modal/modal.tsx
This PR changes the url path for installing the web wallet Firefox extension. Now that the wallet will be available for install in the add-ons store, we no longer want to route users to the hiro.so path.
For details refer to issue #97
No.
No.
> refactor: change url for firefox ext install

- .changeset/honest-rockets-sneeze.md
- packages/connect/src/types/transactions.ts
This PR simply removes the `cancel` boolean added to the tx response bc it isn't needed and was causing issues.
> fix: remove cancel boolean from tx response

- .changeset/ninety-teachers-hunt.md
- package.json
- packages/connect/package.json
This PR moves the `tsdx` package from `dependencies` to `devDependencies`.  This should resolve an error with the Todos App dev tutorial where a downstream dependency was failing a yarn preflight check.
For more details, see https://github.com/blockstack/docs/issues/1170.
No
No
> fix: moved tsdx from dependencies to devDependencies

- .changeset/shaggy-kids-unite.md
- packages/connect-react/src/react/components/connect/context.tsx
- packages/connect-react/src/react/hooks/use-connect.ts
- packages/connect/src/auth.ts
- packages/connect/src/transactions/index.ts
- packages/connect/src/types/auth.ts
- packages/connect/src/types/transactions.ts
This PR exposes the `profile_url` and other properties in the auth response.
For details refer to issue #127
Yes.
TBD.
TBD.
> feat: expose profile url in auth response

- .changeset/smooth-apples-count.md
- packages/connect-ui/package.json
- packages/connect-ui/src/index.html
- packages/connect-ui/stencil.config.ts
- packages/connect/src/ui.ts
- yarn.lock
This PR updates our stenciljs config so that we have access to import `defineCustomElements` via the loader.
For details refer to issue #138 
No.
No.
- Test with the test-app in web wallet
- Make sure the wallet is uninstalled
- Click on `Sign up`
- Make sure the install modal launches w/out an error!
> fix: define custom elements

- .changeset/green-masks-kneel.md
- packages/connect-ui/src/components/modal/modal.scss
- packages/connect-ui/src/components/modal/modal.tsx
- packages/connect-ui/src/components/modal/utils.ts
This PR fixes a few minor ui related issues that I missed implementing the new intro modal design. In addition, I am just adding the unsupported browser text now bc I needed something to use. We can swap out the drawing once we have a new one?
For details refer to issue #143
Adds text for unsupported browser ...will still need to swap out drawing.
Issue: https://github.com/blockstack/connect/issues/95
> fix: unsupported browsers

- .changeset/ninety-taxis-grab.md
- packages/connect-ui/src/components/modal/modal.tsx
This PR updates our wallet download paths to be 'hiro-wallet'. In addition, I have bumped the @stacks/connect package version manually to get it in sync with our current npm published version (6.4.0).
> fix: paths to download the hiro wallet

- packages/connect/src/types/provider.ts
This PR adds the loosely-typed provider method needed for https://github.com/hirosystems/stacks-wallet-web/pull/2378
I reckon there's a design problem here, though. The wallet itself is responsible for the definition its provider, so it's problematic that we first need to modify connect, before being able to modify the wallet. Conceptually, the way I see it, connect consumes the wallet. Yet, this dependency means they consume each other.
<details>
<summary>Note on direction/SIPs</summary>
Eventually, when there are many wallet providers, we may have a full SIP with a provider spec, that might also include tooling such as a distributed provider type package. This would be great. But until then, it's a headache to keep the provider implementation and corresponding types in a separate …
> feat: add stub rpc request types to provider

- .changeset/good-deers-guess.md
- packages/connect/src/signature/index.ts
- packages/connect/src/signature/structuredData.ts
changes ~absolute import to relative. projects using connect may think `src/...` refers to an npm module.
```diff
- from 'src/types/signature';
+ from '../types/signature';
```
> fix: change relative import

- .changeset/yellow-wasps-look.md
- packages/connect-ui/stencil.config.ts
- packages/connect/src/ui.ts
- adds `dist-custom-elements` distribution of `connect-ui`, since rollup-based projects don't handle dynamic loaded stencil well
- the new custom element is loaded (non-dynamically) in the new `showConnectStatic` method (just a copy of `showConnect` without dynamic loading)
using `*Static` would always bundle the connect-ui (ideally only shown when somebody has an incompatible browser, or is missing the wallet extension) into a project. however, developers could adjust their configs (e.g. rollup > `manualChunks`) to achieve similar dynamic loading/chunking, but handled by the last bundler in the build step (rather than stencil before distribution, which is optimized for webpack)
> [poc] add static stencil component

- .changeset/cuddly-rabbits-reply.md
- packages/connect/package.json
- packages/connect/src/signature/structuredData.ts
- packages/connect/src/types/index.ts
- packages/connect/src/types/structuredDataSignature.ts
- yarn.lock
> feat: add support for sip018

- .changeset/forty-plums-count.md
- packages/connect/src/transactions/index.ts
Some logic had been added for the request account flow, that since conflicts with Ledger changes supporting JWTs. This has been removed.
> fix: remove stx address check logic

- .changeset/pink-apples-chew.md
- packages/connect/src/signature/index.ts
- packages/connect/src/signature/structuredData.ts
- packages/connect/src/transactions/index.ts
Like transaction request, we fallback to creating unsigned payloads if no key exists
> fix(ledger): support ledger message signing

- .changeset/modern-ghosts-remember.md
- packages/connect/src/transactions/index.ts
Per this report in https://github.com/hirosystems/stacks-wallet-web/issues/2906, we found that the active STX address a user authed with wasn't being passed to wallet.
We don't need the `hasAppPrivateKey` check before the `getStxAddress` call for Ledger. This has been removed, so the code is shared between software/ledger wallets, so that the default key is no longer omitted.
> fix(ledger): missing stx address prop

- .changeset/eleven-readers-smell.md
- .changeset/nervous-crabs-swim.md
- .changeset/orange-camels-shave.md
- .github/workflows/version.yml
- packages/connect-react/src/react/hooks/use-connect.ts
- packages/connect/package.json
- packages/connect/src/index.ts
- packages/connect/src/profile/index.ts
- packages/connect/src/types/index.ts
- packages/connect/src/types/profile.ts
- packages/connect/src/types/provider.ts
- yarn.lock
> feat: add profile update

- packages/connect/src/transactions/btc.ts
- packages/connect/src/types/transactions.ts
Modified the interface to accept an array of recipient addresses and amounts in order to support multiple recipients. Updated BTCTransferOptions and BTCTransferPayload interfaces. 
Link to relevant issues and documentation: #283 
https://github.com/hirosystems/connect/issues/283#issuecomment-1397938096
Example:
Added ability to add multiple recipients when sending a BTC transfer request
```
const recipients = [
{
recipient: '2NAm1LPPHQQ8AaLhXSYWrpApoCKcyjNJsjf',
amount: '20000'
}
];
await openBTCTransfer(
{
recipients: recipients,
appDetails: {
name: "My App",
icon: window.location.origin + "/my-app-logo.svg",
},
onCancel: () => {
alert("Cancelled");
},
onFinish: (data) => {
alert(`Transaction ID: ${data.txId}`);
alert(`Raw transaction: ${data.txRaw}`);
}, 
});
```
For details refer to …
> feat: multiple btc recipients support

- packages/connect-react/src/react/hooks/use-connect.ts
- packages/connect/README.md
- packages/connect/src/auth.ts
- packages/connect/src/bitcoin/psbt.ts
- packages/connect/src/profile/index.ts
- packages/connect/src/signature/index.ts
- packages/connect/src/signature/structuredData.ts
- packages/connect/src/transactions/index.ts
- packages/connect/src/ui.ts
> - connect `npm install @stacks/connect@7.3.2-alpha.111be12.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.1.2-alpha.111be12.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.1.2-alpha.111be12.0 --save-exact`
Allow a custom `StacksProvider` object to be passed into most Connect methods.
- Attempt at making this issue better: https://github.com/hirosystems/connect/issues/325
```ts
import { authenticate } from '@stacks/connect';
// This will open only the Hiro Wallet
authenticate({ ...normalAuthOptions }, HiroWalletProvider); // <---
```
> feat: allow a custom provider to be passed to Connect methods

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
> - connect `npm install @stacks/connect@7.3.2-alpha.961215c.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.1.2-alpha.961215c.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.1.2-alpha.961215c.0 --save-exact`
Use the following template to create your pull request
Describe the changes that where made in this pull request. When possible start with a user story - short, simple descriptions of a feature told from the perspective of the person who desires the new capability. Be sure to also include the following information:
1. Motivation for change
2. What was changed
3. How does this impact application developers
4. Link to relevant issues and documentation
5. Provide examples of use cases with …
> chore: improve README.md standardization

- packages/connect-react/src/react/hooks/use-connect.ts
- packages/connect/src/transactions/index.ts
- packages/connect/src/types/transactions.ts
Currently, it is not possible to sign a multisig transaction through Stacks wallets using Stacks.js. I added this functionality for Hiro Wallet with [this pull request](https://github.com/hirosystems/wallet/pull/4048). This PR is an initial draft to extend this functionality for Xverse and other potential wallets within Stacks.
This code adds new methods to sign a transaction hex, which should be parsed and displayed on the wallet side. With this method, it will be possible to sign any transaction on Stacks, including sponsored and multisig ones.
This is not a breaking change.
New hex transaction signing methods like `openSignTransaction` and `doSignTransaction` require documentation updates.
Tests are required on the wallet side to check the correctness of the new methods.
> feat: allow transaction as hex for signing

- packages/connect-ui/src/components.d.ts
- packages/connect-ui/src/components/modal/modal.tsx
- packages/connect-ui/src/components/modal/readme.md
- packages/connect/src/ui.ts
> - connect `npm install @stacks/connect@7.4.3-alpha.f84e183.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.2.3-alpha.f84e183.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.1.4-alpha.f84e183.0 --save-exact`
@beguene I added a small tweak, that will not persist the selection for the `authenticate` method, but only for the newly added methods. This way the recent Connect commit is not a "breaking change".
- Introduces the `persistSelection` boolean, to let users have the selection dialog always appear
> refactor: make showConnect not persist, less breaking

- .changeset/ninety-zebras-relax.md
- packages/connect-ui/src/components/modal/modal.tsx
- packages/connect-ui/src/providers.ts
- packages/connect/src/ui.ts
- packages/connect/src/utils.ts
> - connect `npm install @stacks/connect@7.5.1-alpha.31c0272.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.3.1-alpha.31c0272.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.2.1-alpha.31c0272.0 --save-exact`
- closes https://github.com/hirosystems/connect/issues/350
- fixing a bug I worked into the provider persistence for the `showConnect` method
- now works as expected, previously the non-persisting flow would default to old Connect behavior
> fix: pass selected provider when not persisting selection

- .changeset/rare-spiders-pull.md
- .changeset/sixty-schools-remember.md
- packages/connect-ui/src/components.d.ts
- packages/connect-ui/src/components/modal/modal.tsx
- packages/connect-ui/src/components/modal/readme.md
- packages/connect/src/stories/ConnectPage.tsx
- packages/connect/src/ui.ts
> - connect `npm install @stacks/connect@7.6.1-alpha.8ffdb23.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.4.1-alpha.8ffdb23.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.3.1-alpha.8ffdb23.0 --save-exact`
- update scrolling behavior to not let underneath site scroll when modal is open
- adds missing onCancel trigger
thanks to @fess-v 🙏
> fix: update scroll and callbacks

- .changeset/rich-radios-agree.md
- packages/connect/src/utils.ts
> - connect `npm install @stacks/connect@7.8.1-alpha.a1d9796.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.5.1-alpha.a1d9796.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.5.1-alpha.a1d9796.0 --save-exact`
- fixes issue reported by @ECBSJ (url wasn't passed on)
> fix: pass url for new networks

- .changeset/cuddly-colts-beg.md
- packages/connect/src/asigna.ts
Describe the changes that where made in this pull request. When possible start with a user story - short, simple descriptions of a feature told from the perspective of the person who desires the new capability. Be sure to also include the following information:
1. Motivation for change
- Server-side Next.js builds a broken because any import from `@stacks/connect` package will call `initializeAsignaProvider` which tries to access the `window` object without checking if it's defined.
3. What was changed
- Added a condition to check if `window` exists before trying to initialize Asigna Provider
- Added changeset file
5. How does this impact application developers
- Fixes the broken builds
7. Link to relevant issues and documentation
- Closes https://github.com/hirosystems/connect/issues/402 …
> Fix: undefined window on asigna initializer

- .changeset/five-seas-give.md
- .changeset/soft-ravens-yawn.md
- packages/connect/README.md
- packages/connect/src/methods.ts
- packages/connect/src/request.ts
- packages/connect/src/stories/ConnectPage.tsx
- packages/connect/src/types/provider.ts
> - connect `npm install @stacks/connect@8.0.1-alpha.f0449df.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.1-alpha.f0449df.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@7.0.1-alpha.f0449df.0 --save-exact`
- fixes some types (raw method shouldn't be able to use all types)
- adds missing `sendTransfer` method
- fixes some overrides in the missing `sendTransfer` method
> fix: patch raw types overrides

- .changeset/curly-dryers-share.md
- packages/connect/src/request.ts
> - connect `npm install @stacks/connect@8.0.2-alpha.b3d5f88.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.2-alpha.b3d5f88.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@7.0.1-alpha.b3d5f88.0 --save-exact`
- Fix missing override case where Fordefi was missing (as an Xverse-like wallet), so added a helper so it's more clear for the future.
> fix: update override

- .changeset/cuddly-buttons-beam.md
- packages/connect/src/methods.ts
> - connect `npm install @stacks/connect@8.0.2-alpha.b039684.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.2-alpha.b039684.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@7.0.1-alpha.b039684.0 --save-exact`
_tiny followup:_
- add missing broadcast param
> fix: add missing param

- .changeset/happy-ads-compare.md
- packages/connect-ui/src/components.d.ts
- packages/connect-ui/src/components/modal/modal.tsx
- packages/connect-ui/src/components/modal/readme.md
- packages/connect/src/request.ts
> - connect `npm install @stacks/connect@8.0.3-alpha.e842731.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.3-alpha.e842731.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@7.0.1-alpha.e842731.0 --save-exact`
- fixes https://github.com/hirosystems/connect/issues/419
> fix: move persist to only success case

- .changeset/long-jars-pay.md
- packages/connect/src/methods.ts
- packages/connect/src/request.ts
> - connect `npm install @stacks/connect@8.1.2-alpha.0edb52a.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.5-alpha.0edb52a.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.0edb52a.0 --save-exact`
- strip network from xverse sendTransfer calls
> fix: strip network

- .changeset/clever-donuts-cover.md
- packages/connect/src/methods.ts
- packages/connect/src/request.ts
> - connect `npm install @stacks/connect@8.1.2-alpha.5cdeea2.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.5-alpha.5cdeea2.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.5cdeea2.0 --save-exact`
- update overrides for xverse and leather
> fix: update signpsbt overrides

- .changeset/smooth-humans-teach.md
- packages/connect/src/index.ts
> - connect `npm install @stacks/connect@8.1.3-alpha.4180c63.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.6-alpha.4180c63.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.4180c63.0 --save-exact`
- add missing export statement
> fix: add missing export

- .changeset/gentle-colts-dress.md
- .changeset/good-cheetahs-sip.md
- .changeset/great-pugs-cheer.md
- .changeset/little-toys-happen.md
- README.md
- packages/connect-react/README.md
- packages/connect/src/auth.ts
- packages/connect/src/methods.ts
- packages/connect/src/request.ts
- packages/connect/src/storage.ts
- packages/connect/src/stories/ConnectPage.tsx
- packages/connect/src/types/auth.ts
> - connect `npm install @stacks/connect@8.1.4-alpha.38fa12b.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.7-alpha.38fa12b.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.38fa12b.0 --save-exact`
- add missing params to make `connect()` be able to do anything that `getAddresses` can
- fix storage issue where xverse addresses weren't stored correctly
> fix: add params to connect method

- .changeset/flat-lions-hide.md
- packages/connect/src/index.ts
- packages/connect/src/stories/ConnectPage.tsx
> - connect `npm install @stacks/connect@8.1.5-alpha.626c72f.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.8-alpha.626c72f.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.626c72f.0 --save-exact`
- export missing types
> fix: export types

- .changeset/stupid-deers-push.md
- packages/connect/src/request.ts
> - connect `npm install @stacks/connect@8.1.5-alpha.1fc741b.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.8-alpha.1fc741b.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.1fc741b.0 --save-exact`
- add result overrides as well (some wallets have buggy results, or different standards) connect can balance them out in practice
> fix: wallet overrides

- .changeset/serious-planets-laugh.md
- .changeset/twelve-eels-listen.md
- README.md
- packages/connect/README.md
- packages/connect/src/index.ts
- packages/connect/src/request.ts
- packages/connect/src/stories/Connect.stories.tsx
- packages/connect/src/stories/ConnectPage.tsx
> - connect `npm install @stacks/connect@8.1.6-alpha.f852d9a.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.9-alpha.f852d9a.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.f852d9a.0 --save-exact`
- adds missing `approvedProviderIds` as commented by TM
- updates README to make support more clear for Zest
- exports error types
> fix: readme updates and fixes

- .changeset/silent-penguins-worry.md
- packages/connect/src/asigna.ts
Referrer field is unreliable in some cases when user has vpn turned on, so it's enough to check if it's in iframe or not to add AsignaProvider.
> fix: remove referrer check for AsignaProvider iframe injection

- .changeset/slow-rocks-destroy.md
- package-lock.json
- packages/connect/README.md
- packages/connect/src/methods.ts
- packages/connect/src/request.ts
- packages/connect/src/stories/ConnectPage.tsx
> - connect `npm install @stacks/connect@8.1.9-alpha.8efc399.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.12-alpha.8efc399.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.8efc399.0 --save-exact`
Background:
Xverse (and related wallets) require a non-standard param in a method.
This change overrides the params to balance out this behaviour when using the `request` method.
Also updates the demo/testing app add the param in the UI.
> fix: add override for publickey in stx_signMessage

- .changeset/small-tigers-refuse.md
- packages/connect/src/request.ts
- packages/connect/src/stories/ConnectPage.tsx
- packages/connect/tests/request.test.ts
> - connect `npm install @stacks/connect@8.1.10-alpha.4875af9.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.13-alpha.4875af9.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.4875af9.0 --save-exact`
Strip unserializable function values from parameters passed into the request function. This previously caused errors during JSON serialization in some providers.
> fix: remove functions in serializeParams
