hirosystems/connect

src/react/components/screen/screen-body.tsx
src/react/components/screens/finished.tsx
src/react/components/screens/how-it-works.tsx
src/react/components/screens/intro.tsx

This facilitates passing custom styles to the title.

fix: Pass <Title> in directly rather than using argument

---

src/react/components/modal/index.tsx
src/react/components/screen/screen.tsx
src/react/components/screens/finished.tsx
src/react/components/screens/how-it-works.tsx
src/react/components/screens/intro.tsx

Add attributes to buttons to make them the correct size.

fix: Button size

---

src/react/components/screens/intro.tsx

fix: Incorrect intro page footer text size

---

src/react/components/screens/intro.tsx
src/react/components/typography/index.tsx

This fixes two components and adds padding to the title on the intro screen.

Small type style fixes

---

src/react/components/checklist/index.tsx
src/react/components/link.tsx
src/react/components/modal/index.tsx
src/react/components/screen/screen-actions.tsx
src/react/components/screen/screen-body.tsx
src/react/components/screen/screen-footer.tsx
src/react/components/screens/intro.tsx

This fixes https://github.com/blockstack/connect/issues/45: 1, part of 2, 4, 6

Style fixes for modal

---

package.json
src/react/components/screen/screen.tsx
test-app/package.json
test-app/src/App.tsx
test-app/yarn.lock
yarn.lock

related: https://github.com/blockstack/app/pull/175

Feat: update screen to be form when needed

---

README.md
src/auth.ts
src/react/components/connect/context.tsx
src/react/components/modal/index.tsx
src/react/components/powered-by.tsx
src/react/hooks/use-connect.ts

- Removes hover state from "powered by"
- Removes the 'finished' screen after authenticating
- Adds README

Small dev release fixes

---

package.json
webpack.config.js
yarn.lock

Adds in preact in place of react, some ignores taken from blockstack.js, adds in terser for minification. 
1.37mb -> 1.04mb

build: bundle size improvements

---

README.md

Tiny change, only needs 1 reviewer, then feel free to merge.

docs: simplify URL for use with unpkg

---

.github/workflows/version.yml
packages/connect/src/auth.ts
packages/connect/src/transactions/index.ts

Fixes https://github.com/blockstack/stacks-wallet-web/issues/1077

fix: promise handling in `authenticate`

---

.changeset/two-chicken-rest.md
packages/connect/src/types/transactions.ts

replaces https://github.com/blockstack/connect/pull/105

feat: add attachment argument to txbase

---

.changeset/mighty-fishes-drive.md
packages/connect/src/types/transactions.ts
yarn.lock

This PR adds an optional fee to transactions.

fix: add optional tx fee

---

.changeset/eighty-colts-study.md
packages/connect-react/src/react/hooks/use-connect.ts
packages/connect/src/index.ts
packages/connect/src/signature/index.ts
packages/connect/src/transactions/index.ts
packages/connect/src/types/index.ts
packages/connect/src/types/provider.ts
packages/connect/src/types/signature.ts

This adds a doSignature helper and other methods to request a signature 
For more context see
https://github.com/hirosystems/stacks-wallet-web/issues/1051
and 
https://github.com/hirosystems/stacks-wallet-web/pull/2350

feat: support arbitrary message signing

---

.changeset/short-clocks-poke.md
packages/connect-ui/stencil.config.ts
packages/connect/src/ui.ts

i couldn't figure out a simple way to add multiple entry points (exports/modules) with tsdx, so i'm just reverting for now.
we might be able to solve the `static show connect` issue in the future

fix: revert commit 425e771, static show connect

---

packages/connect-ui/package.json
packages/connect-ui/stencil.config.ts
yarn.lock

Fixes build errors for svelte/vue/vite/rollup based projects using connect.
→ https://github.com/ionic-team/stencil/issues/2827
→ https://github.com/ionic-team/stencil/issues/3407

feat: switch to stencil experimental imports

---

.changeset/serious-dolphins-dance.md
packages/connect-react/package.json

- fixes https://github.com/hirosystems/connect/issues/251

fix: fix module field in package

---

packages/connect/src/profile/index.ts
packages/connect/src/types/index.ts
packages/connect/src/types/profile.ts

This PR 
* add missing properties of the ProfileUpdatePayload
* removes unnecessary alias

Add missing payload properties

---

packages/connect/src/signature/structuredData.ts

We were only parsing to string when there's a key, so this was breaking in ledger cases

fix: parse bigint values to string

---

.changeset/chilled-crabs-wonder.md
packages/connect/src/profile/index.ts
packages/connect/src/types/profile.ts

**Problem**
Have been seeing issues with some bundlers and the absolute path is mentioned
**Solution**
Changing to relative for now, although there might be other fixes for this

fix: change absolute paths

---

packages/connect-react/CHANGELOG.md

docs: Add breaking change to Changelog

---

.changeset/clever-onions-tell.md
packages/connect-react/src/react/hooks/use-connect.ts
packages/connect/src/bitcoin/index.ts
packages/connect/src/bitcoin/psbt.ts
packages/connect/src/index.ts
packages/connect/src/types/bitcoin.ts
packages/connect/src/types/index.ts
packages/connect/src/types/provider.ts

This PR adds a `psbtRequest` method to the `StacksProvider`.

feat: support btc psbt

---

.changeset/chilly-spies-grin.md

> - connect `npm install @stacks/connect@7.3.2-alpha.50100ef.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.1.2-alpha.50100ef.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.1.2-alpha.50100ef.0 --save-exact`

chore: add changeset

---

packages/connect/README.md

> - connect `npm install @stacks/connect@7.4.3-alpha.0dccaab.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.2.3-alpha.0dccaab.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.1.4-alpha.0dccaab.0 --save-exact`
Readme updates, Hiro -> Leather
<sub>Also couldn't help fixing a few choice passive voice phrasings 🙂</sub>

chore: update hiro -> leather

---

.changeset/loud-jeans-eat.md
packages/connect-ui/src/components/modal/modal.tsx
packages/connect/src/providers.ts

> - connect `npm install @stacks/connect@7.7.1-alpha.574ca07.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.4.2-alpha.574ca07.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.4.1-alpha.574ca07.0 --save-exact`
- updates link behavior
- removes some incorrect defaults for Leather

fix: update link behavior

---

.gitignore
.vscode/settings.json
package-lock.json
package.json
packages/connect/.storybook/main.ts
packages/connect/package.json
packages/connect/src/stories/Connect.stories.tsx
packages/connect/src/stories/ConnectPage.tsx
packages/connect/src/stories/connect.css
packages/connect/tsconfig.json
tsconfig.json

> - connect `npm install @stacks/connect@7.10.1-alpha.e78ecb0.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@22.6.2-alpha.e78ecb0.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@6.6.1-alpha.e78ecb0.0 --save-exact`
- adds simple add to showcase all methods via input

test: add storybook demo app for testing

---

.changeset/sharp-lobsters-attack.md
.changeset/sixty-socks-ring.md
.changeset/ten-seas-wave.md
packages/connect/README.md
packages/connect/src/index.ts
packages/connect/src/request.ts
packages/connect/src/storage.ts
packages/connect/src/stories/ConnectPage.tsx
packages/connect/src/ui.ts

> - connect `npm install @stacks/connect@8.0.3-alpha.cef2bbd.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.3-alpha.cef2bbd.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@7.0.1-alpha.cef2bbd.0 --save-exact`
wip 🚧

feat: add local storage for address cacheing

---

.changeset/sweet-files-doubt.md
packages/connect/src/request.ts
packages/connect/tests/request.test.ts

> - connect `npm install @stacks/connect@8.0.3-alpha.58f7baa.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.3-alpha.58f7baa.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@7.0.1-alpha.58f7baa.0 --save-exact`
- fixes post condition serialization
- fixes https://github.com/hirosystems/connect/issues/418

fix: update param serialization

---

README.md
packages/connect/README.md

> - connect `npm install @stacks/connect@8.1.5-alpha.0f05287.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.8-alpha.0f05287.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.0f05287.0 --save-exact`
- update readmes

docs: update readme

---

packages/connect/README.md

> - connect `npm install @stacks/connect@8.1.7-alpha.8cfcc02.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.10-alpha.8cfcc02.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.8cfcc02.0 --save-exact`
- minor readme update

docs: remove non sip-030 events

---

.changeset/spicy-dolls-admire.md
package-lock.json
packages/connect/src/asigna.ts

Request method supported for Asigna Iframe, message signature for multisig supported by generateAsignaMessage

Request and message signatures for Asigna

---

packages/connect/src/asigna.ts

> - connect `npm install @stacks/connect@8.1.8-alpha.b8f13b9.0 --save-exact`
> - connect-react `npm install @stacks/connect-react@23.0.11-alpha.b8f13b9.0 --save-exact`
> - connect-ui `npm install @stacks/connect-ui@8.0.1-alpha.b8f13b9.0 --save-exact`
- trivial, run format on save for linter

chore: fix lint errors
